name: Cron Job

on:
  schedule:
    - cron: '0 3 * * SUN'
    
jobs:
  run-cron-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Cron Job
      run: |
